info = {"message": "Setup FrontEnd for LabelStudio Project", "commit": "fe2a36eaeaa0962e0b5da6253db00a34f0642575", "date": "2023-03-16 14:33:57 +0700", "branch": "main", "version": "fe2a36e"}

# This file is automatically generated by version.py
# Do not include it to git!
