info = {"message": "Setup backend django for project", "commit": "b0ae13344e8d2b571b8cf3ae522211d4cb2e9959", "date": "2023-03-21 18:35:25 +0700", "branch": "main", "version": "b0ae133+dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
