info = {"message": "Merge branch 'main' of https://github.com/ThangNguyen211/Label-Studio-Nhom24", "commit": "1657d130b90d74793a14cf9546d8035902df7bf8", "date": "2023-04-26 10:03:47 +0700", "branch": "main", "version": "1657d13+dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
