name: Deploy

on:
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  config:
    name: Config project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SSH into EC2 instance + deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          if [ -d "Label-Studio-Nhom24" ]; then
            cd Label-Studio-Nhom24
            git pull https://github.com/20110725-NguyenHuuThang/Label-Studio-Nhom24.git
            wait
            cd ../
          else
            git clone https://github.com/20110725-NguyenHuuThang/Label-Studio-Nhom24.git
            wait
          fi
          
  stop-old-container:
    name: Stop container
    runs-on: ubuntu-latest
    needs: config
    steps:
    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo docker ps -a --filter ancestor=nguyenthang211/label-studio-nhom24 --format "{{.ID}}" | xargs -r sudo docker stop 
      
  remove-old-container:
    name: Remove container
    needs: stop-old-container
    runs-on: ubuntu-latest
    steps:
    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            sudo docker ps -a --filter ancestor=nguyenthang211/label-studio-nhom24 --format "{{.ID}}" | xargs -r sudo docker rm
          
          
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: remove-old-container
    steps:
    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd Label-Studio-Nhom24
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
 
  start-container:
    name: Start container
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo docker run -d -p 8080:8080 nguyenthang211/label-studio-nhom24 
